### ISSUE TITLE
**Goodpractice, Tidyverse 1.0 & Rlang**

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/regions#12]
Small code improvements for next minor release

**Comment by KKulma** [comment]
some od it is covered in #17

**Comment by antaldaniel** [comment]
In the meantime I added you with writing rights - I forgot that we moved the repo to rOpenGov and you had rights to the antaldaniel/regions version.   

Here is a little puzzle that I was tired for in issue [16](https://github.com/rOpenGov/regions/issues/16)
